name: flutter_internship_2024_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - .env
    - assets/Conversion_path.png
  
    
